### ISSUE TITLE
Trying to run Ubuntu from Mac OS on my Macbook Pro

### ISSUE THREAD

**Issue by gablabelle** [vasi/vmdk-raw-parts#6]
Hello,

Was trying to use `vmdk-raw-parts` to run Ubuntu from Mac OS on my Macbook Pro without luck:

```
$ sudo ./vmdk-raw-parts --platform="darwin" /dev/disk0 ~/Ubuntu 1 2 3 4

àTraceback (most recent call last):
  File "./vmdk-raw-parts", line 362, in <module>
    vmdk = PartitionedVMDK(disk, options)
  File "./vmdk-raw-parts", line 206, in __init__
    self.diskparts = Partitioning(self.diskpath, options)
  File "./vmdk-raw-parts", line 180, in __init__
    disk = open(diskpath)
IOError: [Errno 1] Operation not permitted: '/dev/disk0'
```

Any ideas what I could try next to get this working?

<img width="945" alt="Screen Shot 2019-10-01 at 9 05 02 PM" src="https://user-images.githubusercontent.com/1565793/66010968-314b8580-e48f-11e9-9072-b17f640d0d33.png">

Many thanks for your time and help.

**Comment by vasi** [comment]
I think to access disk0 on recent versions of macOS, you need to [disable SIP](https://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-macos-os-x)
